version: '3'

services:
  kafka-ui:
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui-user-service
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - kafka
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1:9092,kafka-2:9092,kafka-3:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.3
    container_name: zookeeper-user-service
    ports:
      - "2181:2181"
    networks:
      - kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka-1:
    depends_on:
      - zookeeper
    image: confluentinc/cp-kafka:5.4.3
    container_name: kafka-1-user-service
    ports:
      - "9095:9094"
    networks:
      - kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://kafka-1:9092,OUTSIDE://kafka-1:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:9092,OUTSIDE://localhost:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_BROKER_ID: 101
      KAFKA_offsets_topic_replication_factor: 3
    volumes:
      - ./kafka_data/101:/kafka

  kafka-2:
    depends_on:
      - kafka-1
    image: confluentinc/cp-kafka:5.4.3
    container_name: kafka-2-user-service
    ports:
      - "9096:9096"
    networks:
      - kafka
    environment:
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka-2:9092,OUTSIDE://kafka-2:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:9092,OUTSIDE://localhost:9096
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_BROKER_ID: 102
      KAFKA_offsets_topic_replication_factor: 3
    volumes:
      - ./kafka_data/102:/kafka

  kafka-3:
    depends_on:
      - kafka-2
    image: confluentinc/cp-kafka:5.4.3
    container_name: kafka-3-user-service
    ports:
      - "9097:9094"
    networks:
      - kafka
    environment:
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://kafka-3:9092,OUTSIDE://kafka-3:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:9092,OUTSIDE://localhost:9097
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_BROKER_ID: 103
      KAFKA_offsets_topic_replication_factor: 3
    volumes:
      - ./kafka_data/103:/kafka

networks:
  kafka:
    driver: bridge