version: "3"

services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    environment:
      PATH: /go/src/app
    command: app
    restart: always
    network_mode: host
    volumes:
      - $PWD/config.yaml:/config.yaml
    ports:
      - '9000:9000'
      - '9001:9001'

  swagger-ui:
    depends_on:
      - server
    image: swaggerapi/swagger-ui
    volumes:
      - $PWD/pkg/api/api.swagger.json:/data/api.swagger.json
    restart: always
    network_mode: host
    environment:
      SWAGGER_JSON: /data/api.swagger.json
    container_name: swagger-ui
    ports:
      - '80:8080'
