version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: 'receiver-user-service'
    environment:
      PATH: /go/src/receiver
    command: receiver
    restart: always
    volumes:
      - $PWD/config.yaml:/config.yaml
    ports:
      - '9000:9000'
      - '9002:9002'
