version: "3.9"

services:

  postgres:
    image: postgres:14.4
    ports:
      - "127.0.0.1:5432:5432"
    container_name: postgresql-user-service
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "candy_shop"
    volumes:
      - "~/postgresql/data:/var/lib/postgresql/data"
      - "./postgres.conf:/etc/postgresql/postgresql.conf"
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"

  pgbouncer:
    depends_on:
      - postgres
    image: edoburu/pgbouncer:1.17.0
    ports:
      - "127.0.0.1:6432:6432"
    container_name: pgbouncer-user-service
    volumes:
      - "./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini"
      - "./userlist.txt:/etc/pgbouncer/userlist.txt"
