version: '3'

services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui-user-service
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9089,kafka2:9089,kafka3:9089
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.3
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka1:
    depends_on:
      - zookeeper
    image: confluentinc/cp-kafka:5.4.3
    container_name: kafka1
    ports:
      - "9091:9090"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://kafka1:9089,OUTSIDE://kafka1:9090
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:9089,OUTSIDE://localhost:9091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_BROKER_ID: 101

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    volumes:
      - ./kafka_data/101:/kafka

  kafka2:
    depends_on:
      - zookeeper
    image: confluentinc/cp-kafka:5.4.3
    container_name: kafka2
    ports:
      - "9092:9090"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://kafka2:9089,OUTSIDE://kafka2:9090
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:9089,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_BROKER_ID: 102

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    volumes:
      - ./kafka_data/102:/kafka

  kafka3:
    depends_on:
      - zookeeper
    image: confluentinc/cp-kafka:5.4.3
    container_name: kafka3
    ports:
      - "9093:9090"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://kafka3:9089,OUTSIDE://kafka3:9090
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:9089,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_BROKER_ID: 103

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    volumes:
      - ./kafka_data/103:/kafka
