// Code generated by chaingen. DO NOT EDIT.

package models

func NewUserListParams() *UserListParams {
	return &UserListParams{}
}

func (u *UserListParams) LimitSet(Limit uint64) *UserListParams {
	u.Limit = Limit
	return u
}

func (u *UserListParams) OffsetSet(Offset uint64) *UserListParams {
	u.Offset = Offset
	return u
}

func (u *UserListParams) OrderSet(Order bool) *UserListParams {
	u.Order = Order
	return u
}
